name: basic unit testing2
on: workflow_dispatch
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu user
        run: echo "user is $GITHUB_ACTOR"
      - name: windows user
        run: echo "user is $env:GITHUB_ACTOR"
    

