name: basic unit testing2
on: workflow_dispatch
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: echo "deployed"
      - name: download artifact
        uses: actions/download-artifact@v3
        with: 
          name: my-artifacts
      - name: list files
        run: ls -l
    

