name: basic unit testing2
on: workflow_dispatch
jobs:
  deploy-to-server:
    environment: test
    runs-on: ubuntu-latest
    env:
      fullname: hi
    steps:
      - name: action secret
        run: echo "user is ${{secrets.MY_ACTION_SECRET}}"
      - name: environment secret
        run: echo "user is $fullname"
      - name: env specific
        run: echo "value is ${{secrets.MY_ACTION_SECRET1}}"
    

